version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "2004:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/travel
#      SPRING_DATASOURCE_USERNAME: hoang
#      SPRING_DATASOURCE_PASSWORD: 123456

volumes:
  postgres-data:
    driver: local
